Category translation name
CodeYourFuture/legodi pull request #104
Opened 2017-12-04 19:00 UTC by kharazzoro

2017-12-06 15:22 UTC, kabaros commented on server/models/Category.js
> +    titleTranslation:{
this can be improved to be an array of objects
```js
titleTranslations: [{am: 'amharic translation', ar: 'arabic translation']
```

Like that you can have any number of translations - not just arabic and amharic

2017-12-06 16:15 UTC, kharazzoro commented on server/models/Category.js
> +    titleTranslation:{
@kabaros Updated

2017-12-07 10:04 UTC, kabaros requested changes

2017-12-07 10:04 UTC, kabaros commented on server/views/admin-add-category.hbs
> +<<<<<<< HEAD
The conflicts here are not properly fixed.

2017-12-07 10:04 UTC, kabaros commented on server/views/admin-edit-article.hbs
> +<<<<<<< HEAD
again, merge conflicts not resolved properly.

2017-12-08 16:21 UTC, kabaros approved these changes

2017-12-08 16:21 UTC, merged