improving the position of the components prevent drop menu to overrid…
CodeYourFuture/legodi pull request #107
Opened 2017-12-05 07:38 UTC by kharazzoro

…e them

2017-12-05 16:10 UTC, kabaros requested changes

2017-12-05 16:10 UTC, kabaros commented on client/src/components/About/about.css
> +.About{
small letters for class name (also use dashes, so `about-page` as opposed to `aboutPage`)

2017-12-05 16:10 UTC, kabaros commented on client/src/components/Categories/CategoriesOverview/category.css
> +#root .SingleCategory{
same here - wrong naming convention for css `single-category`

2017-12-05 16:10 UTC, kabaros commented on client/src/containers/Setting/Setting.js
> +            <div className="row app-select-language">
I don't understand what you changed here - how the does Language Selector look like now?

2017-12-06 15:20 UTC, kabaros requested changes
send me screenshots please

2017-12-06 16:25 UTC, kharazzoro commented
![image](https://user-images.githubusercontent.com/26529612/33672423-0ff78260-daa2-11e7-979e-727b9e789470.png)

2017-12-06 16:26 UTC, kharazzoro commented
![image](https://user-images.githubusercontent.com/26529612/33672455-279c6fde-daa2-11e7-91bd-363decc6ba6d.png)

2017-12-06 16:27 UTC, kharazzoro commented
![image](https://user-images.githubusercontent.com/26529612/33672515-498b966a-daa2-11e7-8011-3723fe194992.png)

2017-12-06 16:30 UTC, kharazzoro commented
![image](https://user-images.githubusercontent.com/26529612/33672701-c54a33ba-daa2-11e7-88ff-2dae5fe83fbe.png)

2017-12-07 10:00 UTC, kabaros commented
I still don't think you need all of this to achieve what you want to achieve - let's review it together on Saturday.

2017-12-10 11:32 UTC, kabaros approved these changes

2017-12-10 11:32 UTC, merged