serverSetUpAdminDummyPage
CodeYourFuture/legodi pull request #14
Opened 2017-10-24 12:42 UTC by anthonythuo2320

2017-10-24 18:49 UTC, anthonythuo2320 commented
solved the merge conflict

2017-10-24 21:13 UTC, kabaros requested changes

2017-10-24 21:13 UTC, kabaros commented on server/app.js
> + serverSetUpAdminDummyPage
this is not resolved properly - you should delete these lines serverSetup.... and master. This will break the code.

2017-10-26 17:44 UTC, kabaros approved these changes

2017-10-26 17:45 UTC, merged