admin list categories[without bootstrap style]
CodeYourFuture/legodi pull request #32
Opened 2017-10-29 23:27 UTC by kharazzoro

admin list categories[without bootstrap style]

2017-10-29 23:53 UTC, kabaros requested changes
if you're using the bootstrap from the CDN then remove it from package.json (and all the files in public) - the reason the style is not working is probably because you didn't wrap it in a container and such.

Also don't copy the files in each handlebars - just use a layout handlebar as we did in the projects before.

2017-10-29 23:57 UTC, kharazzoro commented
done

On Sun, Oct 29, 2017 at 11:53 PM, kabaros <notifications@github.com> wrote:

> *@kabaros* requested changes on this pull request.
>
> if you're using the bootstrap from the CDN then remove it from
> package.json (and all the files in public) - the reason the style is not
> working is probably because you didn't wrap it in a container and such.
>
> Also don't copy the files in each handlebars - just use a layout handlebar
> as we did in the projects before.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeYourFuture/legodi/pull/32#pullrequestreview-72715993>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AZTPTDLCHJRXDxOf33vSbX3jYgQHvRCrks5sxRAWgaJpZM4QKhkA>
> .
>

2017-10-30 00:12 UTC, kabaros requested changes

2017-10-30 00:12 UTC, kabaros commented on server/routes/admin.js
> +const categoryDB = require("../dbClients/categoriesDB");
why are you importing categoryDB - you can just use categoryClient (it's the same module).

2017-10-30 00:19 UTC, kabaros commented on server/views/index.hbs
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorig
you don't need stylesheets again here - they come from layout

2017-10-30 00:26 UTC, kabaros commented on server/routes/admin.js
> +const categoryDB = require("../dbClients/categoriesDB");
@kharazzoro did you read this comment

2017-10-30 00:26 UTC, kabaros commented on server/views/index.hbs
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorig
@kharazzoro

2017-10-30 00:50 UTC, kabaros commented on server/views/index.hbs
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorig
this comment @kharazzoro

2017-10-30 07:18 UTC, merged